services:
  master:
    build: .
    ports:
      - "8089:8089"
    command: poetry run locust --master
    
  worker:
    build: .
    command: poetry run locust --worker --master-host master

  locust-exporter:
    image: containersol/locust_exporter
    environment:
      - LOCUST_EXPORTER_URI=http://master:8089
    ports:
      - 9646:9646
    depends_on:
      - master

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile-prometheus
    ports:
      - "9090:9090"
    depends_on:
      - locust-exporter
