services:
  master:
    build: .
    ports:
      - "8089:8089"
    command: poetry run locust --master
    
  worker:
    build: .
    command: poetry run locust --worker --master-host master

  locust-exporter:
    image: containersol/locust_exporter
    network_mode: "host"
    ports:
      - "9646:9646"
    # command: go run main.go --locust.uri http://localhost:8089 --web.listen-address :9694

  prometheus:
    build:
      context: .
      dockerfile: Dockerfile-prometheus
    ports:
      - "9090:9090"
