global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

scrape_configs:
  - job_name: "locust"
    scrape_interval: 2s
    static_configs:
      - targets: ["locust-exporter:9646"]
