version: '3.3'
services:
  mongo:
    ports:
      - '27017:27017'
    container_name: mongo-db
    restart: always
    logging:
      options:
        max-size: 1g
    environment:
        - MONGO_INITDB_ROOT_USERNAME=mongoadmin
        - MONGO_INITDB_ROOT_PASSWORD=catbug
    image: mongo
