version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  server:
    build: .
    container_name: express-server
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  worker:
    build: .
    container_name: job-worker
    command: ["node", "worker.js"]
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
